export const projects = [
  {
    num: "01",
    tag: "Healthcare · Microservices",
    date: "Jan 2025 – Dec 2025",
    title: "MediBridge",
    description:
      "A production-grade healthcare management platform built on 5 independent microservices — Doctor, Patient, Booking, Payment, and Auth. Each service owns its own database and communicates asynchronously through Apache Kafka, meaning a payment failure never blocks a booking. JWT-based stateless auth with Spring Security handles role-based access for Doctors and Patients separately.",
    highlights: [
      "5 independent microservices — each with its own DB",
      "Kafka async notifications — fully decoupled from core flow",
      "JWT + RBAC — separate Doctor and Patient roles",
      "Spring Cloud Gateway + Netflix Eureka",
      "React.js frontend with Doctor Admin + Patient Dashboard",
    ],
    techs: [
      "Java", "Spring Boot", "Apache Kafka", "JWT",
      "Spring Security", "React.js", "MySQL",
      "API Gateway", "Eureka", "Docker",
    ],
    github: "https://github.com/Abhishek-fullstack-dev/medibridge-fullstack-microservices",
    live: null,
  },
  {
    num: "02",
    tag: "E-Commerce · Event-Driven",
    date: "Jan 2026 – Present",
    title: "Event-Order System",
    description:
      "A distributed order processing system designed around the Saga choreography pattern — each service publishes and reacts to events without a central orchestrator. If payment fails, the Saga automatically triggers compensation transactions to roll back inventory. Kafka Retry topics and Dead Letter Queues ensure zero message loss even when downstream services go down.",
    highlights: [
      "Saga choreography — automatic compensation on failure",
      "Kafka Retry topics + Dead Letter Queue for fault tolerance",
      "4 services: Order, Inventory, Payment, Notification",
      "GitHub Actions CI/CD + SonarQube quality gates",
      "Live on AWS EC2 + RDS via Docker Compose",
    ],
    techs: [
      "Java", "Spring Boot", "Apache Kafka", "Saga Pattern",
      "AWS EC2", "AWS RDS", "Docker", "GitHub Actions", "SonarQube",
    ],
    github: "https://github.com/Abhishek-fullstack-dev/event-order-system",
    live: null,
  },
  {
    num: "03",
    tag: "SaaS · AI-Powered",
    date: "2026",
    title: "QuizCraft AI",
    description:
      "An AI-powered quiz SaaS where users paste any topic and instantly get 10 smart MCQs generated by OpenAI. Spring Boot backend with JWT auth, PostgreSQL for quiz history, leaderboards, and performance analytics. The OpenAI prompt is engineered to return structured JSON so questions map directly to DB entities without manual parsing.",
    highlights: [
      "OpenAI API — structured JSON quiz generation",
      "JWT auth + per-user quiz history tracking",
      "Leaderboard + performance analytics dashboard",
      "Spring Boot + React.js + PostgreSQL on AWS",
      "Docker + Nginx + SSL on AWS EC2",
    ],
    techs: [
      "Java", "Spring Boot", "OpenAI API",
      "React.js", "PostgreSQL", "AWS EC2", "Docker", "JWT",
    ],
    github: "https://github.com/Abhishek-fullstack-dev/quizcraft-ai",
    live: "https://quizcraft.live",
  },
]